export const quizzes = [
  {
    id: 1,
    titleEnglish: 'Beginner Vocabulary Quiz',
    titleArabic: 'اختبار المفردات للمبتدئين',
    time: 10,
    level: 'Beginner',
    type: 'Vocabulary',
  },
  {
    id: 2,
    titleEnglish: 'Beginner Grammar Quiz',
    titleArabic: 'اختبار القواعد للمبتدئين',
    time: 10,
    level: 'Beginner',
    type: 'Grammar',
  },
  {
    id: 3,
    titleEnglish: 'Intermediate Vocabulary Quiz',
    titleArabic: 'اختبار المفردات للمتوسطين',
    time: 10,
    level: 'Intermediate',
    type: 'Vocabulary',
  },
  {
    id: 4,
    titleEnglish: 'Intermediate Grammar Quiz',
    titleArabic: 'اختبار القواعد للمتوسطين',
    time: 10,
    level: 'Intermediate',
    type: 'Grammar',
  },
  {
    id: 5,
    titleEnglish: 'Advanced Vocabulary Quiz',
    titleArabic: 'اختبار المفردات للمتقدمين',
    time: 10,
    level: 'Advanced',
    type: 'Vocabulary',
  },
  {
    id: 6,
    titleEnglish: 'Advanced Grammar Quiz',
    titleArabic: 'اختبار القواعد للمتقدمين',
    time: 10,
    level: 'Advanced',
    type: 'Grammar',
  },
  {
    id: 7,
    titleEnglish: 'Beginner Reading Quiz',
    titleArabic: 'اختبار القراءة للمبتدئين',
    time: 10,
    level: 'Beginner',
    type: 'Reading',
  },
  {
    id: 8,
    titleEnglish: 'Intermediate Reading Quiz',
    titleArabic: 'اختبار القراءة للمتوسطين',
    time: 10,
    level: 'Intermediate',
    type: 'Reading',
  },
  {
    id: 9,
    titleEnglish: 'Advanced Reading Quiz',
    titleArabic: 'اختبار القراءة للمتقدمين',
    time: 10,
    level: 'Advanced',
    type: 'Reading',
  },
  {
    id: 10,
    titleEnglish: 'Beginner Listening Quiz',
    titleArabic: 'اختبار الاستماع للمبتدئين',
    time: 10,
    level: 'Beginner',
    type: 'Listening',
  },
  {
    id: 11,
    titleEnglish: 'Intermediate Listening Quiz',
    titleArabic: 'اختبار الاستماع للمتوسطين',
    time: 10,
    level: 'Intermediate',
    type: 'Listening',
  },
  {
    id: 12,
    titleEnglish: 'Advanced Listening Quiz',
    titleArabic: 'اختبار الاستماع للمتقدمين',
    time: 10,
    level: 'Advanced',
    type: 'Listening',
  },
  {
    id: 13,
    titleEnglish: 'Beginner Writing Quiz',
    titleArabic: 'اختبار الكتابة للمبتدئين',
    time: 10,
    level: 'Beginner',
    type: 'Writing',
  },
  {
    id: 14,
    titleEnglish: 'Intermediate Writing Quiz',
    titleArabic: 'اختبار الكتابة للمتوسطين',
    time: 10,
    level: 'Intermediate',
    type: 'Writing',
  },
  {
    id: 15,
    titleEnglish: 'Advanced Writing Quiz',
    titleArabic: 'اختبار الكتابة للمتقدمين',
    time: 10,
    level: 'Advanced',
    type: 'Writing',
  },
];
