export const feedback = [
  {
    name: 'Alice Johnson',
    type: 'feedback',
    text: 'I really enjoyed the new features in the application.',
    date: new Date('2023-12-01'),
  },
  {
    name: 'Bob Smith',
    type: 'problem',
    text: 'I encountered an error while trying to upload my file.',
    date: new Date('2023-12-02'),
  },
  {
    name: 'Carol White',
    type: 'feedback',
    text: 'The user interface is very intuitive and easy to use.',
    date: new Date('2023-12-03'),
  },
  {
    name: 'David Brown',
    type: 'problem',
    text: 'There was a delay in the response time of the support team.',
    date: new Date('2023-12-22'),
  },
  {
    name: 'Eve Wilson',
    type: 'feedback',
    text: 'I would like to have more options for customizing my profile.',
    date: new Date('2023-12-05'),
  },
  {
    name: 'Frank Miller',
    type: 'problem',
    text: 'I encountered an error while trying to upload my file.',
    date: new Date('2023-12-06'),
  },
  {
    name: 'Grace Davis',
    type: 'feedback',
    text: 'I really enjoyed the new features in the application.',
    date: new Date('2023-12-07'),
  },
  {
    name: 'Henry Garcia',
    type: 'problem',
    text: 'There was a delay in the response time of the support team.',
    date: new Date('2023-12-08'),
  },
  {
    name: 'Isabella Rodriguez',
    type: 'feedback',
    text: 'The user interface is very intuitive and easy to use.',
    date: new Date('2023-12-09'),
  },
  {
    name: 'Jack Wilson',
    type: 'problem',
    text: 'I encountered an error while trying to upload my file.',
    date: new Date('2023-10-10'),
  },
  {
    name: 'Karen Anderson',
    type: 'feedback',
    text: 'I would like to have more options for customizing my profile.',
    date: new Date('2023-12-11'),
  },
  {
    name: 'Larry Thomas',
    type: 'problem',
    text: 'There was a delay in the response time of the support team.',
    date: new Date('2023-11-12'),
  },
  {
    name: 'Mary Taylor',
    type: 'feedback',
    text: 'I really enjoyed the new features in the application.',
    date: new Date('2023-12-13'),
  },
  {
    name: 'Nancy Garcia',
    type: 'problem',
    text: 'I encountered an error while trying to upload my file.',
    date: new Date('2023-07-14'),
  },
];
