export const lessons = [
  {
    id: 11111,
    titleEnglish: 'Benefits of Green Tea',
    titleArabic: 'فوائد الشاي الأخضر',
    level: 'Beginner',
    type: 'Reading',
    imageLink: 'https://assets.rbl.ms/19152954/origin.jpg',
    video: false,
  },
  {
    id: 0,
    titleEnglish: 'Letters',
    titleArabic: 'الحروف',
    level: 'Beginner',
    type: 'Vocabulary',
    imageLink: 'https://www.lebanesearabicinstitute.com/wp-content/uploads/2017/02/Alphabet.jpg',
    video: false,
  },
  {
    id: 1,
    titleEnglish: 'Days of the Week',
    titleArabic: 'أيام الأسبوع',
    level: 'Beginner',
    type: 'Vocabulary',
    imageLink:
      'https://ecdn.teacherspayteachers.com/thumbitem/%D8%A3%D9%8A%D8%A7%D9%85-%D8%A7%D9%84%D8%A3%D8%B3%D8%A8%D9%88%D8%B9-5774095-1624390540/original-5774095-1.jpg',
  },
  {
    id: 2,
    titleEnglish: 'Months of the Year',
    titleArabic: 'أشهر السنة',
    level: 'Beginner',
    type: 'Vocabulary',
    imageLink: '',
  },
  {
    id: 44444,
    titleEnglish: 'The Water Cycle',
    titleArabic: 'دورة المياه',
    level: 'Intermediate',
    type: 'Writing',
    imageLink:
      'https://st.adda247.com/https://adda247jobs-wp-assets-adda247.s3.ap-south-1.amazonaws.com/jobs/wp-content/uploads/sites/2/2022/07/23130600/SmartSelect_20220723-125355_Office.jpg',
    video: false,
  },
  {
    id: 55555,
    titleEnglish: 'The Solar System',
    titleArabic: 'المجموعة الشمسية',
    level: 'Advanced',
    type: 'Grammar',
    imageLink: '',
    video: false,
  },
  {
    id: 66666,
    titleEnglish: 'The Human Body',
    titleArabic: 'جسم الانسان',
    level: 'Advanced',
    type: 'Listening',
    imageLink: 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Internal_organs.png',
    video: false,
  },
  {
    id: 5,
    titleEnglish: 'Colors',
    titleArabic: 'الألوان',
    level: 'Beginner',
    type: 'Vocabulary',
    imageLink:
      'https://blog.khamsat.com/wp-content/uploads/2021/04/%D8%B9%D9%84%D9%85-%D9%86%D9%81%D8%B3-%D8%A7%D9%84%D8%A3%D9%84%D9%88%D8%A7%D9%86.jpg',
  },
  {
    id: 6,
    titleEnglish: 'Numbers',
    titleArabic: 'الأرقام',
    level: 'Beginner',
    type: 'Vocabulary',
    imageLink:
      'https://media.licdn.com/dms/image/D4D12AQFARwQFHC3zww/article-cover_image-shrink_720_1280/0/1662013068402?e=2147483647&v=beta&t=V-YMzEdx1xwEQvnhZMllzYqpdfDldeGY-m0b6nrKwKY',
  },
  {
    id: 7,
    titleEnglish: 'Animals',
    titleArabic: 'الحيوانات',
    level: 'Intermediate',
    type: 'Vocabulary',
    imageLink:
      'https://static.webteb.net/images/content/tbl_articles_article_17204_6546e0b64c-15a7-4501-95a0-864e67932185.jpg',
  },
  {
    id: 77777,
    titleEnglish: 'How to Write a Resume',
    titleArabic: 'كيفية كتابة السيرة الذاتية',
    level: 'Beginner',
    type: 'Reading',
    imageLink: '',
    video: false,
  },
  {
    id: 88888,
    titleEnglish: 'How to Interview for a Job',
    titleArabic: 'كيفية مقابلة للحصول على وظيفة',
    level: 'Beginner',
    type: 'Grammar',
    imageLink: 'https://gsb.hse.ru/pubs/share/direct/408305373.png',
    video: true,
  },
  {
    id: 99999,
    titleEnglish: 'The History of the World',
    titleArabic: 'تاريخ العالم',
    level: 'Intermediate',
    type: 'Reading',
    imageLink: 'https://suttonhighnews.net/wp-content/uploads/2022/03/Nash-History-Journal.png',
    video: false,
  },
  {
    id: 100000,
    titleEnglish: 'The Different Types of Government',
    titleArabic: 'الأنواع المختلفة للحكومات',
    level: 'Intermediate',
    type: 'Writing',
    imageLink: 'https://www.whitehouse.gov/wp-content/uploads/2021/01/us-capitol.jpg',
    video: false,
  },
  {
    id: 100001,
    titleEnglish: 'The Economy',
    titleArabic: 'الاقتصاد',
    level: 'Advanced',
    type: 'Listening',
    imageLink:
      'https://protium.co.in/wp-content/uploads/2022/09/how-does-lending-contribute-to-the-economy.jpg',
    video: false,
  },
  {
    id: 100002,
    titleEnglish: 'The Environment',
    titleArabic: 'البيئة',
    level: 'Advanced',
    type: 'Reading',
    imageLink:
      'https://images.theconversation.com/files/427100/original/file-20211018-17-7bf8no.jpg?ixlib=rb-1.1.0&rect=7%2C7%2C4985%2C3315&q=20&auto=format&w=320&fit=clip&dpr=2&usm=12&cs=strip',
    video: true,
  },
  {
    id: 100003,
    titleEnglish: 'The Future of Work',
    titleArabic: 'مستقبل العمل',
    level: 'Advanced',
    type: 'Writing',
    imageLink: '',
    video: false,
  },
  {
    id: 100004,
    titleEnglish: 'Learning a New Language',
    titleArabic: 'تعلم لغة جديدة',
    level: 'Beginner',
    type: 'Writing',
    imageLink:
      'https://gurmentor.com/wp-content/uploads/2020/11/gurmentor.com-best-language-learning-methods-and-teaching-approaches-explained-2020-11-17_16-21-09_140956.png',
    video: false,
  },
  {
    id: 100005,
    titleEnglish: 'Coding for Beginners',
    titleArabic: 'البرمجة للمبتدئين',
    level: 'Beginner',
    type: 'Listening',
    imageLink:
      'https://teachyourkidscode.com/wp-content/uploads/2022/02/best-coding-language-for-games.jpg',
    video: true,
  },
  {
    id: 8,
    titleEnglish: 'Food',
    titleArabic: 'الطعام',
    level: 'Intermediate',
    type: 'Vocabulary',
    imageLink: 'https://www.ibelieveinsci.com/wp-content/uploads/Variety_Image_747px.jpg',
  },
  {
    id: 9,
    titleEnglish: 'Body Parts',
    titleArabic: 'أجزاء الجسم',
    level: 'Advanced',
    type: 'Vocabulary',
    imageLink: '',
  },
  {
    id: 100006,
    titleEnglish: 'Public Speaking',
    titleArabic: 'التحدث أمام الجمهور',
    level: 'Intermediate',
    type: 'Grammar',
    imageLink:
      'https://images.inc.com/uploaded_files/image/1920x1080/getty_614138202_2000133520009280253_328692.jpg',
    video: false,
  },
  {
    id: 100007,
    titleEnglish: 'Time Management',
    titleArabic: 'إدارة الوقت',
    level: 'Intermediate',
    type: 'Listening',
    imageLink:
      'https://www.simplilearn.com/ice9/free_resources_article_thumb/Proven_Time_Management_Tips_and_Strategies_for_students.jpg',
    video: true,
  },
  {
    id: 100008,
    titleEnglish: 'Negotiation',
    titleArabic: 'التفاوض',
    level: 'Advanced',
    type: 'Reading',
    imageLink:
      'https://ideas.darden.virginia.edu/sites/default/files/styles/large/public/2021-07/202107_Modica_Negotiation%404x.png?itok=kvFVo--I',
    video: false,
  },
  {
    id: 100009,
    titleEnglish: 'Leadership',
    titleArabic: 'القيادة',
    level: 'Advanced',
    type: 'Writing',
    imageLink:
      'https://s40424.pcdn.co/in/wp-content/uploads/2022/06/what-is-leadership.jpg.optimal.jpg',
    video: true,
  },
  {
    id: 100010,
    titleEnglish: 'Personal Development',
    titleArabic: 'التطوير الشخصي',
    level: 'Intermediate',
    type: 'Grammar',
    imageLink: 'https://unlockedpotentials.com/wp-content/uploads/2022/10/life-coach-in-dubai.jpg',
    video: false,
  },
];
